# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hD1ZgkSCZobDOHRJHGZ5DHir-X9y2T47
"""

import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten, MaxPooling2D, ELU
from keras.layers.normalization import BatchNormalization

from keras.datasets import fashion_mnist

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
x_train = x_train.reshape(60000,28,28,1)
x_test  = x_test.reshape(10000,28,28,1)
x_test, x_train = x_test / 255.0, x_train / 255.0

model = Sequential()
#add model layers
model.add(BatchNormalization())
model.add(Conv2D(48, kernel_size=3, activation='relu', input_shape=x_train.shape[1:4]))
model.add(Conv2D(64, kernel_size=3, activation='relu'))


model.add(Flatten())
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=3)
model.summary()

print(y_test[:4])
model.predict(x_test[:4])